### PR TITLE
[fix] Use UIFont.lineHeight for calculate the number of CALayer used in …

### LINKED ISSUE #239: Multiline skeleton don't work on UILabel with font size lower than 17
### What did you do?

Skeleton UILabel on 2 lines with small font (14)

### What did you expect to happen?

2 layer rect

### What happened instead?

1 layer rect

### Steps to reproduce the behavior

- Put UILabel with fixed width (and self sized height)
- Set number of lines to 2
- Add long text (longer than 2 lines)
- Set font size to lower than 17 (eg: 14)
- Show skeleton 

### SkeletonView Environment

**SkeletonView version:** 1.8.2
**Xcode version:** 11.3.1
**Swift version:** 5

### PR DESCRIPTION
**Pull request by damien-danglard**
Use UIFont.lineHeight for calculate the number of CALayer used in multiline Skeleton UILabel

close #239

### CODE REVIEW

File: Sources/Extensions/CALayer+Extensions.swift [hunk 1]
```diff
@@ -28,6 +28,16 @@ extension CAGradientLayer {
     }
 }
 
+struct SkeletonMultilinesLayerConfig {
```
Comment (Juanpe) [inline Sources/Extensions/CALayer+Extensions.swift]: 😍

**Comment by Juanpe** [comment]
Thanks for contributing :)

**Comment by damien-danglard** [comment]
> Thanks for contributing :)

You're welcome.
Thanks for approving my contribution :)
