### PR TITLE
fix UITableViewAlertForLayoutOutsideViewHierarchy warning

### LINKED ISSUE #383: UITableViewAlertForLayoutOutsideViewHierarchy warning
Still getting this warning when trying to immediately show a skeletonView on a `UITableView`

> [TableView] Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window.

### PR DESCRIPTION
**Pull request by michaelhenry**
### Summary

close #383 

avoid having this warning
> [TableView] Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window.

* [x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/main/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/main/CODE_OF_CONDUCT.md).

### CODE REVIEW

File: Sources/SubviewsSkeletonables.swift [hunk 1]
```diff
@@ -14,7 +14,8 @@ extension UIView {
 
 extension UITableView {
     override var subviewsToSkeleton: [UIView] {
-        visibleCells + visibleSectionHeaders + visibleSectionFooters
+		guard window != nil else { return [] }
```
Comment (Juanpe) [inline Sources/SubviewsSkeletonables.swift:17]: I think this could be a good workaround. Because of that, I think we should include a comment here, explaining why we are checking if the `window` is `nil`. WDYT?

**Comment by Juanpe** [comment]
Hi @michaelhenry, thanks for your first contribution! 🎉

The looks fine, I only added a comment in order to provide more context about why this workaround 🙂

**Comment by michaelhenry** [comment]
Thanks @Juanpe 🍻

File: Sources/SubviewsSkeletonables.swift (hunk 1 above)
Comment (michaelhenry) [reply Sources/SubviewsSkeletonables.swift:20]: @Juanpe I now updated PR. Please check. thanks

Comment (Juanpe) [reply Sources/SubviewsSkeletonables.swift:20]: I think is enough :) Thx

**Review by Juanpe — APPROVED** [review]

**Comment by Juanpe** [comment]
Thanks again for your contribution, this PR will be included in the next version 🎉
